"""픽셀 스프라이트 생성기: python3 tools/gen_sprites.py  →  assets/pixel/*.png"""
import struct, zlib, random, os

SCALE = 8
PAL = {
    '.': None, 'k': '#2b2140', 'r': '#ff6b8b', 'R': '#c9486a', 'w': '#f5e6c8', 'b': '#d98c6a',
    'y': '#f1fa8c', 'c': '#8be9fd', 'p': '#ff79c6', 'u': '#bd93f9', 'g': '#5fb36b', 'G': '#3b7a4a',
    'n': '#a8704c', 'N': '#7a4a30', 's': '#b4b4cc', 'S': '#7c7c96', 'W': '#fbfbf5', 'o': '#ffb86c',
    'O': '#e8883a', 'x': '#d9d9e8', 'a': '#7ed08a', 'l': '#6b4430', 'e': '#9a9ab4',
}

def hexrgb(h): return tuple(int(h[i:i+2], 16) for i in (1, 3, 5))

def write_png(path, rows, SCALE=SCALE):
    h = len(rows) * SCALE; w = len(rows[0]) * SCALE
    raw = b''
    for row in rows:
        line = b''
        for ch in row:
            px = bytes([0, 0, 0, 0]) if PAL[ch] is None else bytes(hexrgb(PAL[ch]) + (255,))
            line += px * SCALE
        raw += (b'\x00' + line) * SCALE
    def chunk(t, d):
        c = struct.pack('>I', len(d)) + t + d
        return c + struct.pack('>I', zlib.crc32(t + d) & 0xffffffff)
    png = b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 6, 0, 0, 0)) \
        + chunk(b'IDAT', zlib.compress(raw)) + chunk(b'IEND', b'')
    open(path, 'wb').write(png)

SPR = {}
SPR['house'] = """
................
................
......kkkk......
.....krrrrk.....
....krrrrrrk....
...krrRrrRrrk...
..krrrrrrrrrrk..
.kkkkkkkkkkkkkk.
.kbbbbbbbbbbbbk.
.kbbwwbbbbwwbbk.
.kbbwcbbbbwcbbk.
.kbbbbbkkbbbbbk.
.kbbbbkuukbbbbk.
.kbbbbkuukbbbbk.
.kkkkkkkkkkkkkk.
................
"""
SPR['tower'] = """
......kkkk......
.....kppppk.....
....kppppppk....
....kkkkkkkk....
....kssssssk....
....ksccccsk....
....kscWWcsk....
....ksccccsk....
....kssssssk....
....ksyyyysk....
....ksyyyysk....
....kssssssk....
...kssssssssk...
..kssSSSSSSssk..
..kkkkkkkkkkkk..
................
"""
SPR['library'] = """
................
................
......kkkk......
.....kuuuuk.....
....kuuuuuuk....
..kkkkkkkkkkkk..
.kuuuuuuuuuuuuk.
.kWWWWWWWWWWWWk.
.kWsWsWWWWsWsWk.
.kWsWsWWWWsWsWk.
.kWWWWWkkWWWWWk.
.kWsWsWkyykWsWk.
.kWWWWWkyykWWWk.
.kkkkkkkkkkkkkk.
..NNNNNNNNNNNN..
................
"""
SPR['ruins'] = """
................
................
................
................
................
.........kk.....
........kssk....
...kk...kSsk....
..kssk.kkssk.k..
..kSsskkSSsskk..
.kkSSssSSSsSSkk.
.kSSnSSssSnSSSk.
kkSnnSSSSSnnSSkk
kSSSSkSSSSSkSSSk
kkkkkkkkkkkkkkkk
................
"""
SPR['hammer'] = """
.......kk.......
......knnk......
......knnk......
......knnk......
......knnk......
......knnk......
......knnk......
......knnk......
......knnk......
..kkkkkkkkkkkk..
..kssssssssssk..
..kSSSSSSSSSSk..
..kkkkkkkkkkkk..
................
................
................
"""
SPR['speaker_on'] = """
................
................
.......W........
......WW....W...
..WWWWWW.....W..
..WWWWWW..W..W..
..WWWWWW...W..W.
..WWWWWW...W..W.
..WWWWWW...W..W.
..WWWWWW..W..W..
..WWWWWW.....W..
......WW....W...
.......W........
................
................
................
"""
SPR['speaker_off'] = """
................
................
.......W........
......WW........
..WWWWWW........
..WWWWWW..W...W.
..WWWWWW...W.W..
..WWWWWW....W...
..WWWWWW...W.W..
..WWWWWW..W...W.
..WWWWWW........
......WW........
.......W........
................
................
................
"""
SPR['flame'] = """
................
.......O........
......OO........
......OOO...O...
.....OOOO..OO...
....OOOOOO.OOO..
....OOooOOOOOO..
...OOooooOOOOO..
...OOoooooOOOO..
...OOooyyooOO...
...OOoyyyyoOO...
....OooyyyoO....
.....OOooOO.....
......OOOO......
................
................
"""
def canvas():
    return [['.'] * 16 for _ in range(16)]

def box(g, x0, y0, x1, y1, fill):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            edge = x in (x0, x1) or y in (y0, y1)
            g[y][x] = 'k' if edge else fill

def put(g, x, y, ch):
    g[y][x] = ch

def to_str(g):
    return '\n'.join(''.join(r) for r in g)

# 오두막: 짚지붕 + 나무 벽
g = canvas()
for i, (w, fill) in enumerate([(4, 'o'), (6, 'o'), (8, 'O'), (10, 'o'), (12, 'O')]):
    x0 = (16 - w) // 2
    for x in range(x0, x0 + w):
        g[4 + i][x] = 'k' if (i == 0 or x in (x0, x0 + w - 1)) else fill
for x in range(2, 14):
    put(g, x, 8, 'k')
box(g, 3, 9, 12, 14, 'n')
box(g, 7, 11, 8, 14, 'N')
put(g, 5, 11, 'y'); put(g, 10, 11, 'y')
SPR['hut'] = to_str(g)

# 성: 양옆 탑 + 중앙 탑 + 성문 + 깃발
g = canvas()
box(g, 1, 8, 14, 14, 's')       # 성벽
box(g, 1, 4, 4, 14, 'S')        # 왼쪽 탑
box(g, 11, 4, 14, 14, 'S')      # 오른쪽 탑
box(g, 6, 3, 9, 9, 's')         # 중앙 탑
for x in (1, 3, 11, 13):        # 흉벽
    put(g, x, 3, 'k')
for x in (6, 8):
    put(g, x, 2, 'k')
put(g, 7, 0, 'k'); put(g, 7, 1, 'k')   # 깃대
put(g, 8, 0, 'r'); put(g, 9, 0, 'r'); put(g, 8, 1, 'r')
box(g, 6, 10, 9, 14, 'N')       # 성문
put(g, 7, 10, 'k'); put(g, 8, 10, 'k')
put(g, 2, 7, 'c'); put(g, 12, 7, 'c'); put(g, 7, 5, 'c'); put(g, 8, 5, 'c')
SPR['castle'] = to_str(g)

BODY_LOWER = """
..kBBBBBBBBBBk..
..kBBBBBBBBBBk..
..kBBkBBBBkBBk..
..kBBBBBBBBBBk..
..kBBBBppBBBBk..
..kBBBBBBBBBBk..
...kBBBBBBBBk...
....kkkkkkkk....
................
""".strip().split('\n')
def mascot(upper, B, extra=None):
    rows = ['................'] + upper.strip().split('\n') + BODY_LOWER
    rows = [r.replace('B', B) for r in rows]
    return '\n'.join(rows)
SPR['bear'] = mascot("""
................
................
................
..kkkk....kkkk..
.knnnnk..knnnnk.
.knnnnkkkknnnnk.
""", 'n')
SPR['cat'] = mascot("""
................
................
...k........k...
..kok......kok..
..koookkkkkook..
..kooooooooook..
""", 'o')
SPR['rabbit'] = mascot("""
...kk......kk...
..kWWk....kWWk..
..kWpk....kpWk..
..kWpk....kpWk..
..kWWkkkkkkWWk..
..kWWWWWWWWWWk..
""", 'W')

# 타일
random.seed(7)
grass = [['g'] * 16 for _ in range(16)]
for _ in range(14):
    x, y = random.randrange(15), random.randrange(15)
    grass[y][x] = 'G'; grass[y + 1][x] = 'G'
SPR['grass'] = '\n'.join(''.join(r) for r in grass)
fog = [['S'] * 16 for _ in range(16)]
for cx, cy in [(3, 4), (10, 3), (6, 10), (12, 11), (2, 12)]:
    for dx in range(-2, 3):
        for dy in range(-1, 2):
            if 0 <= cx + dx < 16 and 0 <= cy + dy < 16 and abs(dx) + abs(dy) < 4:
                fog[cy + dy][cx + dx] = 's' if dy else 'x'
SPR['fog'] = '\n'.join(''.join(r) for r in fog)

# 아이소메트릭 땅 블록 (32x24): 위는 마름모 윗면, 아래는 좌/우 옆면
def iso_block(top_a, top_b, left, right):
    W, H, T = 32, 24, 8
    def in_dia(x, y, oy=0):
        return abs(x - 15.5) / 16 + abs(y - oy - 7.5) / 8 <= 1
    grid = [['.'] * W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            if in_dia(x, y):
                grid[y][x] = top_a if ((x // 4) + (y // 2)) % 2 == 0 else top_b
            elif y >= 8 and in_dia(x, y, T) or (y >= 8 and any(in_dia(x, y, d) for d in range(1, T + 1))):
                grid[y][x] = left if x < 16 else right
    # 타일끼리 이어져 보이도록 검은 테두리는 그리지 않는다
    return [''.join(r) for r in grid]

ISO = {
    'tile_grass': iso_block('a', 'g', 'N', 'n'),
}
os.makedirs('assets/pixel', exist_ok=True)
for name, rows in ISO.items():
    write_png(f'assets/pixel/{name}.png', rows, SCALE=4)
for name, art in SPR.items():
    rows = [r for r in art.strip('\n').split('\n')]
    assert len(rows) == 16, (name, len(rows))
    for i, r in enumerate(rows):
        assert len(r) == 16, (name, i, len(r), r)
    write_png(f'assets/pixel/{name}.png', rows)
print('ok', list(SPR))
