"""픽셀 스프라이트 생성기: python3 tools/gen_sprites.py  →  assets/pixel/*.png"""
import struct, zlib, random, os

SCALE = 8
PAL = {
    '.': None, 'k': '#2b2140', 'r': '#ff6b8b', 'R': '#c9486a', 'w': '#f5e6c8', 'b': '#d98c6a',
    'y': '#f1fa8c', 'c': '#8be9fd', 'p': '#ff79c6', 'u': '#bd93f9', 'g': '#5fb36b', 'G': '#3b7a4a',
    'n': '#a8704c', 'N': '#7a4a30', 's': '#b4b4cc', 'S': '#7c7c96', 'W': '#fbfbf5', 'o': '#ffb86c',
    'O': '#e8883a', 'x': '#d9d9e8', 'a': '#7ed08a', 'l': '#6b4430', 'e': '#9a9ab4',
}

def hexrgb(h): return tuple(int(h[i:i+2], 16) for i in (1, 3, 5))

def write_png(path, rows, SCALE=SCALE):
    h = len(rows) * SCALE; w = len(rows[0]) * SCALE
    raw = b''
    for row in rows:
        line = b''
        for ch in row:
            px = bytes([0, 0, 0, 0]) if PAL[ch] is None else bytes(hexrgb(PAL[ch]) + (255,))
            line += px * SCALE
        raw += (b'\x00' + line) * SCALE
    def chunk(t, d):
        c = struct.pack('>I', len(d)) + t + d
        return c + struct.pack('>I', zlib.crc32(t + d) & 0xffffffff)
    png = b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 6, 0, 0, 0)) \
        + chunk(b'IDAT', zlib.compress(raw)) + chunk(b'IEND', b'')
    open(path, 'wb').write(png)

SPR = {}
SPR['house'] = """
................
................
......kkkk......
.....krrrrk.....
....krrrrrrk....
...krrRrrRrrk...
..krrrrrrrrrrk..
.kkkkkkkkkkkkkk.
.kbbbbbbbbbbbbk.
.kbbwwbbbbwwbbk.
.kbbwcbbbbwcbbk.
.kbbbbbkkbbbbbk.
.kbbbbkuukbbbbk.
.kbbbbkuukbbbbk.
.kkkkkkkkkkkkkk.
................
"""
SPR['tower'] = """
......kkkk......
.....kppppk.....
....kppppppk....
....kkkkkkkk....
....kssssssk....
....ksccccsk....
....kscWWcsk....
....ksccccsk....
....kssssssk....
....ksyyyysk....
....ksyyyysk....
....kssssssk....
...kssssssssk...
..kssSSSSSSssk..
..kkkkkkkkkkkk..
................
"""
SPR['library'] = """
................
................
......kkkk......
.....kuuuuk.....
....kuuuuuuk....
..kkkkkkkkkkkk..
.kuuuuuuuuuuuuk.
.kWWWWWWWWWWWWk.
.kWsWsWWWWsWsWk.
.kWsWsWWWWsWsWk.
.kWWWWWkkWWWWWk.
.kWsWsWkyykWsWk.
.kWWWWWkyykWWWk.
.kkkkkkkkkkkkkk.
..NNNNNNNNNNNN..
................
"""
SPR['ruins'] = """
................
................
................
................
................
.........kk.....
........kssk....
...kk...kSsk....
..kssk.kkssk.k..
..kSsskkSSsskk..
.kkSSssSSSsSSkk.
.kSSnSSssSnSSSk.
kkSnnSSSSSnnSSkk
kSSSSkSSSSSkSSSk
kkkkkkkkkkkkkkkk
................
"""
SPR['hammer'] = """
.......kk.......
......knnk......
......knnk......
......knnk......
......knnk......
......knnk......
......knnk......
......knnk......
......knnk......
..kkkkkkkkkkkk..
..kssssssssssk..
..kSSSSSSSSSSk..
..kkkkkkkkkkkk..
................
................
................
"""
SPR['speaker_on'] = """
................
................
.......W........
......WW....W...
..WWWWWW.....W..
..WWWWWW..W..W..
..WWWWWW...W..W.
..WWWWWW...W..W.
..WWWWWW...W..W.
..WWWWWW..W..W..
..WWWWWW.....W..
......WW....W...
.......W........
................
................
................
"""
SPR['speaker_off'] = """
................
................
.......W........
......WW........
..WWWWWW........
..WWWWWW..W...W.
..WWWWWW...W.W..
..WWWWWW....W...
..WWWWWW...W.W..
..WWWWWW..W...W.
..WWWWWW........
......WW........
.......W........
................
................
................
"""
SPR['flame'] = """
................
.......O........
......OO........
......OOO...O...
.....OOOO..OO...
....OOOOOO.OOO..
....OOooOOOOOO..
...OOooooOOOOO..
...OOoooooOOOO..
...OOooyyooOO...
...OOoyyyyoOO...
....OooyyyoO....
.....OOooOO.....
......OOOO......
................
................
"""
def canvas():
    return [['.'] * 16 for _ in range(16)]

def box(g, x0, y0, x1, y1, fill):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            edge = x in (x0, x1) or y in (y0, y1)
            g[y][x] = 'k' if edge else fill

def put(g, x, y, ch):
    g[y][x] = ch

def to_str(g):
    return '\n'.join(''.join(r) for r in g)

# 오두막: 짚지붕 + 나무 벽
g = canvas()
for i, (w, fill) in enumerate([(4, 'o'), (6, 'o'), (8, 'O'), (10, 'o'), (12, 'O')]):
    x0 = (16 - w) // 2
    for x in range(x0, x0 + w):
        g[4 + i][x] = 'k' if (i == 0 or x in (x0, x0 + w - 1)) else fill
for x in range(2, 14):
    put(g, x, 8, 'k')
box(g, 3, 9, 12, 14, 'n')
box(g, 7, 11, 8, 14, 'N')
put(g, 5, 11, 'y'); put(g, 10, 11, 'y')
SPR['hut'] = to_str(g)

# 성: 양옆 탑 + 중앙 탑 + 성문 + 깃발
g = canvas()
box(g, 1, 8, 14, 14, 's')       # 성벽
box(g, 1, 4, 4, 14, 'S')        # 왼쪽 탑
box(g, 11, 4, 14, 14, 'S')      # 오른쪽 탑
box(g, 6, 3, 9, 9, 's')         # 중앙 탑
for x in (1, 3, 11, 13):        # 흉벽
    put(g, x, 3, 'k')
for x in (6, 8):
    put(g, x, 2, 'k')
put(g, 7, 0, 'k'); put(g, 7, 1, 'k')   # 깃대
put(g, 8, 0, 'r'); put(g, 9, 0, 'r'); put(g, 8, 1, 'r')
box(g, 6, 10, 9, 14, 'N')       # 성문
put(g, 7, 10, 'k'); put(g, 8, 10, 'k')
put(g, 2, 7, 'c'); put(g, 12, 7, 'c'); put(g, 7, 5, 'c'); put(g, 8, 5, 'c')
SPR['castle'] = to_str(g)

BODY_LOWER = """
..kBBBBBBBBBBk..
..kBBBBBBBBBBk..
..kBBkBBBBkBBk..
..kBBBBBBBBBBk..
..kBBBBppBBBBk..
..kBBBBBBBBBBk..
...kBBBBBBBBk...
....kkkkkkkk....
................
""".strip().split('\n')
def mascot(upper, B, extra=None):
    rows = ['................'] + upper.strip().split('\n') + BODY_LOWER
    rows = [r.replace('B', B) for r in rows]
    return '\n'.join(rows)
SPR['bear'] = mascot("""
................
................
................
..kkkk....kkkk..
.knnnnk..knnnnk.
.knnnnkkkknnnnk.
""", 'n')
SPR['cat'] = mascot("""
................
................
...k........k...
..kok......kok..
..koookkkkkook..
..kooooooooook..
""", 'o')
SPR['rabbit'] = mascot("""
...kk......kk...
..kWWk....kWWk..
..kWpk....kpWk..
..kWpk....kpWk..
..kWWkkkkkkWWk..
..kWWWWWWWWWWk..
""", 'W')

# 타일
random.seed(7)
grass = [['g'] * 16 for _ in range(16)]
for _ in range(14):
    x, y = random.randrange(15), random.randrange(15)
    grass[y][x] = 'G'; grass[y + 1][x] = 'G'
SPR['grass'] = '\n'.join(''.join(r) for r in grass)
fog = [['S'] * 16 for _ in range(16)]
for cx, cy in [(3, 4), (10, 3), (6, 10), (12, 11), (2, 12)]:
    for dx in range(-2, 3):
        for dy in range(-1, 2):
            if 0 <= cx + dx < 16 and 0 <= cy + dy < 16 and abs(dx) + abs(dy) < 4:
                fog[cy + dy][cx + dx] = 's' if dy else 'x'
SPR['fog'] = '\n'.join(''.join(r) for r in fog)

# 아이소메트릭 땅 블록 (32x24): 위는 마름모 윗면, 아래는 좌/우 옆면
def iso_block(top_a, top_b, left, right):
    W, H, T = 32, 24, 8
    def in_dia(x, y, oy=0):
        return abs(x - 15.5) / 16 + abs(y - oy - 7.5) / 8 <= 1
    grid = [['.'] * W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            if in_dia(x, y):
                grid[y][x] = top_a if ((x // 4) + (y // 2)) % 2 == 0 else top_b
            elif y >= 8 and in_dia(x, y, T) or (y >= 8 and any(in_dia(x, y, d) for d in range(1, T + 1))):
                grid[y][x] = left if x < 16 else right
    # 타일끼리 이어져 보이도록 검은 테두리는 그리지 않는다
    return [''.join(r) for r in grid]

ISO = {
    'tile_grass': iso_block('a', 'g', 'N', 'n'),
}
os.makedirs('assets/pixel', exist_ok=True)
for name, rows in ISO.items():
    write_png(f'assets/pixel/{name}.png', rows, SCALE=4)
for name, art in SPR.items():
    rows = [r for r in art.strip('\n').split('\n')]
    assert len(rows) == 16, (name, len(rows))
    for i, r in enumerate(rows):
        assert len(r) == 16, (name, i, len(r), r)
    write_png(f'assets/pixel/{name}.png', rows)
print('ok', list(SPR))


# ───────────────────────── 캐릭터 만들기용 스프라이트 ─────────────────────────
# 몸(종 × 색) 36장 + 모자 오버레이 4장. 앱에서 몸 위에 모자를 겹쳐 그린다.
# 템플릿 표기: B=몸 색, D=몸 색의 짙은 톤(귀 안쪽), k=윤곽선

CHAR_SPECIES = {
    'bear': """
................
................
................
..kkkk....kkkk..
.kBBBBk..kBBBBk.
.kBDDBkkkkBDDBk.
""",
    'cat': """
................
................
...k........k...
..kBk......kBk..
..kBDkkkkkkDBk..
..kBBBBBBBBBBk..
""",
    'rabbit': """
...kk......kk...
..kBBk....kBBk..
..kBDk....kDBk..
..kBDk....kDBk..
..kBBkkkkkkBBk..
..kBBBBBBBBBBk..
""",
    'fox': """
................
..kk........kk..
.kBBk......kBBk.
.kBDBkkkkkkBDBk.
.kBBBBBBBBBBBBk.
..kBBBBBBBBBBk..
""",
}
CHAR_COLORS = {  # id: (몸 색, 짙은 톤)
    'brown': ('#a8704c', '#7a4a30'),
    'cream': ('#f5e6c8', '#d9c49a'),
    'gray': ('#b4b4cc', '#7c7c96'),
    'orange': ('#ffb86c', '#e8883a'),
    'pink': ('#ffa6c9', '#e87ba8'),
    'white': ('#fbfbf5', '#d9d9e8'),
    'blue': ('#8be9fd', '#55b6cf'),
    'purple': ('#bd93f9', '#8f6bd6'),
    'mint': ('#7ee787', '#4cb85a'),
}
HATS = {
    'hardhat': """
................
................
................
................
......kkkk......
.....kyyyyk.....
....kyyyyyyk....
...kkkkkkkkkk...
................
................
................
................
................
................
................
................
""",
    'crown': """
................
................
................
................
.....k.kk.k.....
.....kyyyyk.....
.....kyryyk.....
....kkkkkkkk....
................
................
................
................
................
................
................
................
""",
    'bow': """
................
................
................
................
........kkk.kkk.
........kppkppk.
........kkk.kkk.
................
................
................
................
................
................
................
................
................
""",
    'cap': """
................
................
................
................
................
......kkkk......
.....kccccck....
....kcccccckkkk.
................
................
................
................
................
................
................
................
""",
}

def build_char(template, base, dark):
    rows = ['................'] + template.strip('\n').split('\n') + BODY_LOWER
    assert len(rows) == 16, len(rows)
    return [r.replace('B', 'Q').replace('D', 'R') for r in rows], base, dark

import copy
_pal_backup = dict(PAL)
for sp, tpl in CHAR_SPECIES.items():
    for cid, (base, dark) in CHAR_COLORS.items():
        rows, b, d = build_char(tpl, base, dark)
        PAL['Q'], PAL['R'] = b, d
        for r in rows:
            assert len(r) == 16, (sp, r)
        write_png(f'assets/pixel/char_{sp}_{cid}.png', rows)
for hid, art in HATS.items():
    rows = art.strip('\n').split('\n')
    assert len(rows) == 16, hid
    for r in rows:
        assert len(r) == 16, (hid, r)
    write_png(f'assets/pixel/hat_{hid}.png', rows)

# 앱에서 쓰는 이미지 목록(require)을 자동으로 만든다
lines = ["// 자동 생성 파일 — tools/gen_sprites.py 를 실행하면 다시 만들어진다. 직접 수정하지 마세요.", "", "export const SPECIES = %s as const;" % list(CHAR_SPECIES),
         "export const COLOR_IDS = %s as const;" % list(CHAR_COLORS),
         "export const COLOR_HEX = %s as const;" % {k: v[0] for k, v in CHAR_COLORS.items()},
         "export const HAT_IDS = ['none', %s] as const;" % ', '.join(repr(h) for h in HATS), "",
         "export const BODY_IMAGES: Record<string, number> = {"]
for sp in CHAR_SPECIES:
    for cid in CHAR_COLORS:
        lines.append(f"  '{sp}_{cid}': require('../../assets/pixel/char_{sp}_{cid}.png'),")
lines += ["};", "", "export const HAT_IMAGES: Record<string, number> = {"]
for hid in HATS:
    lines.append(f"  {hid}: require('../../assets/pixel/hat_{hid}.png'),")
lines += ["};", ""]
open('src/lib/characterAssets.ts', 'w').write('\n'.join(lines))
print('characters ok')


# ───────────────────────── 설정/프로필용 아이콘 (흰색, 앱에서 tintColor로 색을 입힌다) ─────────────────────────
import math
from PIL import Image, ImageDraw, ImageFont

def blank():
    return [['.'] * 16 for _ in range(16)]

def field(fn):
    g = blank()
    for y in range(16):
        for x in range(16):
            if fn(x - 7.5, y - 7.5):
                g[y][x] = 'W'
    return g

ICONS = {}
ICONS['target'] = field(lambda dx, dy: (lambda r: r <= 1.7 or 3.2 <= r <= 4.4 or 5.6 <= r <= 6.9)(math.hypot(dx, dy)))
ICONS['user'] = field(lambda dx, dy: (math.hypot(dx, dy + 3.2) <= 3.1) or (dy >= 1.2 and dy <= 6.5 and abs(dx) <= 2.2 + (dy - 1.2) * 0.85 and (abs(dx) <= 6.3)))
ICONS['plus'] = field(lambda dx, dy: (abs(dx) <= 1.0 and abs(dy) <= 5.5) or (abs(dy) <= 1.0 and abs(dx) <= 5.5))
def gear(dx, dy):
    r = math.hypot(dx, dy)
    ring = 3.0 <= r <= 5.0
    tooth = (r <= 7.0 and r >= 4.5) and (abs(dx) <= 1.2 or abs(dy) <= 1.2 or abs(abs(dx) - abs(dy)) <= 1.3)
    return ring or tooth
ICONS['gear'] = field(gear)
shield_widths = [0, 0, 10, 12, 12, 12, 12, 12, 11, 10, 8, 6, 4, 2, 0, 0]
g = blank()
for y, w in enumerate(shield_widths):
    for x in range(8 - w // 2, 8 + (w + 1) // 2):
        if w:
            g[y][x] = 'W'
for y in range(4, 9):          # 방패 속 홈(선택) — 가운데를 비운다
    g[y][7] = '.'; g[y][8] = '.'
ICONS['shield'] = g
bell = """
................
.......WW.......
......WWWW......
.....WWWWWW.....
.....WWWWWW.....
.....WWWWWW.....
....WWWWWWWW....
....WWWWWWWW....
...WWWWWWWWWW...
...WWWWWWWWWW...
..WWWWWWWWWWWW..
................
......WWWW......
.......WW.......
................
................
"""
ICONS['bell'] = [list(r) for r in bell.strip('\n').split('\n')]
share = """
................
.......WW.......
......WWWW......
.....WWWWWW.....
....WWWWWWWW....
.......WW.......
.......WW.......
..WW...WW...WW..
..WW...WW...WW..
..WW........WW..
..WW........WW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
................
................
................
"""
ICONS['share'] = [list(r) for r in share.strip('\n').split('\n')]

# 글자 아이콘: 픽셀 폰트로 한 글자를 그려서 가져온다
def glyph(ch):
    f = ImageFont.truetype('node_modules/@expo-google-fonts/press-start-2p/400Regular/PressStart2P_400Regular.ttf', 16)
    im = Image.new('L', (16, 16), 0)
    d = ImageDraw.Draw(im)
    w = d.textlength(ch, font=f)
    d.text(((16 - w) / 2, 0), ch, font=f, fill=255)
    return [['W' if im.getpixel((x, y)) > 110 else '.' for x in range(16)] for y in range(16)]
ICONS['help'] = glyph('?')
# 돋보기: 고리 + 손잡이
def search(dx, dy):
    cx, cy = -1.6, -1.6
    r = math.hypot(dx - cx, dy - cy)
    ring = 3.4 <= r <= 5.2
    handle = (dx - cy > 2.2) and abs((dx - cx) - (dy - cy)) <= 1.4 and dx <= 6.6 and dy <= 6.6
    return ring or handle
ICONS['search'] = field(search)
# 막대 그래프 (3개)
g = blank()
for x0, x1, top in [(2, 4, 8), (7, 9, 3), (12, 14, 6)]:
    for y in range(top, 14):
        for x in range(x0, x1 + 1):
            g[y][x] = 'W'
for x in range(1, 16):
    g[14][x] = 'W'
ICONS['chart'] = g

for name, g in ICONS.items():
    rows = [''.join(r) for r in g]
    assert len(rows) == 16 and all(len(r) == 16 for r in rows), (name, len(rows), [len(r) for r in rows])
    write_png(f'assets/pixel/icon_{name}.png', rows)

# characterAssets.ts 와 같은 방식으로 아이콘 목록 파일을 만든다
lines = ["// 자동 생성 파일 — tools/gen_sprites.py 를 실행하면 다시 만들어진다. 직접 수정하지 마세요.", "", "export const ICON_IMAGES = {"]
for name in ICONS:
    lines.append(f"  {name}: require('../../assets/pixel/icon_{name}.png'),")
lines += ["} as const;", "export type IconName = keyof typeof ICON_IMAGES;", ""]
open('src/lib/iconAssets.ts', 'w').write('\n'.join(lines))
print('icons ok', list(ICONS))
